/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  ApolloClient,
} from 'apollo-client';
import {
  DocumentNode,
} from 'graphql';
import {
  OnMutationReadyFn,
} from './components/apollo-mutation/types';
import {
  OnQueryReadyFn,
} from './components/apollo-query/types';


export namespace Components {

  interface ApolloClientController {
    'create': (client: ApolloClient<any>) => Promise<void>;
    'getClient': () => Promise<ApolloClient<any>>;
  }
  interface ApolloClientControllerAttributes extends StencilHTMLAttributes {}

  interface ApolloMutation {
    'mutation': DocumentNode;
    'onReady': OnMutationReadyFn;
  }
  interface ApolloMutationAttributes extends StencilHTMLAttributes {
    'mutation'?: DocumentNode;
    'onReady'?: OnMutationReadyFn;
  }

  interface ApolloProvider {
    'client': ApolloClient<any>;
  }
  interface ApolloProviderAttributes extends StencilHTMLAttributes {
    'client'?: ApolloClient<any>;
  }

  interface ApolloQuery {
    'onReady': OnQueryReadyFn<any>;
    'query': DocumentNode;
  }
  interface ApolloQueryAttributes extends StencilHTMLAttributes {
    'onReady'?: OnQueryReadyFn<any>;
    'query'?: DocumentNode;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ApolloClientController': Components.ApolloClientController;
    'ApolloMutation': Components.ApolloMutation;
    'ApolloProvider': Components.ApolloProvider;
    'ApolloQuery': Components.ApolloQuery;
  }

  interface StencilIntrinsicElements {
    'apollo-client-controller': Components.ApolloClientControllerAttributes;
    'apollo-mutation': Components.ApolloMutationAttributes;
    'apollo-provider': Components.ApolloProviderAttributes;
    'apollo-query': Components.ApolloQueryAttributes;
  }


  interface HTMLApolloClientControllerElement extends Components.ApolloClientController, HTMLStencilElement {}
  var HTMLApolloClientControllerElement: {
    prototype: HTMLApolloClientControllerElement;
    new (): HTMLApolloClientControllerElement;
  };

  interface HTMLApolloMutationElement extends Components.ApolloMutation, HTMLStencilElement {}
  var HTMLApolloMutationElement: {
    prototype: HTMLApolloMutationElement;
    new (): HTMLApolloMutationElement;
  };

  interface HTMLApolloProviderElement extends Components.ApolloProvider, HTMLStencilElement {}
  var HTMLApolloProviderElement: {
    prototype: HTMLApolloProviderElement;
    new (): HTMLApolloProviderElement;
  };

  interface HTMLApolloQueryElement extends Components.ApolloQuery, HTMLStencilElement {}
  var HTMLApolloQueryElement: {
    prototype: HTMLApolloQueryElement;
    new (): HTMLApolloQueryElement;
  };

  interface HTMLElementTagNameMap {
    'apollo-client-controller': HTMLApolloClientControllerElement
    'apollo-mutation': HTMLApolloMutationElement
    'apollo-provider': HTMLApolloProviderElement
    'apollo-query': HTMLApolloQueryElement
  }

  interface ElementTagNameMap {
    'apollo-client-controller': HTMLApolloClientControllerElement;
    'apollo-mutation': HTMLApolloMutationElement;
    'apollo-provider': HTMLApolloProviderElement;
    'apollo-query': HTMLApolloQueryElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
