/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "first": string;
        "last": string;
    }
    interface MyFunctionalComponent {
        "first": string;
        "last": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyFunctionalComponentElement extends Components.MyFunctionalComponent, HTMLStencilElement {
    }
    var HTMLMyFunctionalComponentElement: {
        prototype: HTMLMyFunctionalComponentElement;
        new (): HTMLMyFunctionalComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-functional-component": HTMLMyFunctionalComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "first"?: string;
        "last"?: string;
    }
    interface MyFunctionalComponent {
        "first"?: string;
        "last"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-functional-component": MyFunctionalComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-functional-component": LocalJSX.MyFunctionalComponent & JSXBase.HTMLAttributes<HTMLMyFunctionalComponentElement>;
        }
    }
}
