/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import 'stencil-apollo';
import '@stencil/state-tunnel';


export namespace Components {

  interface MyFunctionalComponent {
    'first': string;
    'last': string;
  }
  interface MyFunctionalComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }

  interface MyComponent {
    'first': string;
    'last': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyFunctionalComponent': Components.MyFunctionalComponent;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'my-functional-component': Components.MyFunctionalComponentAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLMyFunctionalComponentElement extends Components.MyFunctionalComponent, HTMLStencilElement {}
  var HTMLMyFunctionalComponentElement: {
    prototype: HTMLMyFunctionalComponentElement;
    new (): HTMLMyFunctionalComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-functional-component': HTMLMyFunctionalComponentElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'my-functional-component': HTMLMyFunctionalComponentElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
